### ISSUE TITLE
mod broken

### ISSUE THREAD

**Issue by Zoarjt** [spire-winder/Balatro-Draft#1]
choosing the deck opens all draft tags and only allows one option, menu glitches and the draft crate and skip button overlay remain on top making the game unplayable

![image](https://github.com/user-attachments/assets/017bfc18-f6fb-4d39-b27c-46765b4fce37)

![image](https://github.com/user-attachments/assets/d96ec781-3453-42a2-bb53-90212ce39d46)

**Comment by spire-winder** [comment]
This is most likely caused by a mod conflict. What other mods are you running?

**Comment by Zoarjt** [comment]
your correct my mistake, new to modding Balatro so apologies for the ticket
